backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "lore"
    label: "Lore Book"
    files:
      - file: "content/lore/pages.json"
        label: "Pages"
        name: "pagesfile"
        fields:
          - label: "Pages"
            name: "pages"
            widget: "list"
            fields:
              - { label: "Page Number", name: "pg", widget: "number" }

              - label: "Blocks"
                name: "blocks"
                widget: "list"
                types:
                  - label: "Text"
                    name: "text"
                    widget: "object"
                    fields:
                      - { label: "Side", name: "side", widget: "select", options: ["left", "right"] }
                      - { label: "Text", name: "text", widget: "markdown" }

                  - label: "Image"
                    name: "image"
                    widget: "object"
                    fields:
                      - { label: "Side", name: "side", widget: "select", options: ["left", "right"] }
                      - { label: "Image", name: "src", widget: "image" }

                  - label: "Video"
                    name: "video"
                    widget: "object"
                    fields:
                      - { label: "Side", name: "side", widget: "select", options: ["left", "right"] }
                      - { label: "Video File", name: "src", widget: "file" }
